name: derry
description: A script manager to help you define script shortcuts and use them effortlessly, and performantly.
version: 1.4.3
repository: https://github.com/frencojobs/derry

environment:
  sdk: ">=2.10.0 <3.0.0"

executables:
  derry:

dependencies:
  args: ^2.3.1
  console: ^4.1.0
  equatable: ^2.0.5
  ffi: ^2.0.1
  path: ^1.8.2
  string_similarity: ^2.0.0
  yaml: ^3.1.1

dev_dependencies:
  build_runner: ^2.3.2
  build_version: ^2.1.1
  lint: ^1.10.0
  test: ^1.21.7

scripts: derry.yaml
